version: '3.1'

services:

  db:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: creek_db
      USER: root
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "8050:3306"
    cap_add:
      - SYS_NICE

  adminer:
    image: adminer
    ports:
      - 8080:8080
    container_name: creek-secrets1
